

# Setup
title:            Everyday Computing
tagline:             
url:              http://blog.everydaycomputing.org
images:           https://github.com/everydaycomputing/everydaycomputing.github.io/raw/master/public/images/
date_format:          '%B %d, %Y'

# Jekyll configuration
paginate:            4
baseurl:             ""
permalink:           pretty
excerpt_separator:  <!--excerpt-->



# Owner configuration
# name and email are required (change code to remove these)
# (leave the rest blank to disable the corresponding sharing button)
owner:
    name:
    email:
    github:  everydaycomputing
    twitter: everydayCS
    linkedin:
    facebook:
    google_plus:
    youtube:

# Disqus comments configuration (leave blank to disable comments)
disqus_shortname: 'everydaycomputing'
analytics_id: 'UA-81184314-1'

# Post sharing icons
sharing:
    twitter: true
    linkedin: true
    facebook: true
    google_plus: true
    reddit: true


# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/poole/poole

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Don't include these files when processing
exclude: [everydaycomputing.github.io.xcodeproj,archive]

# Conversion
#
# See https://idratherbewriting.com/2016/02/21/bug-with-kramdown-and-rouge-with-github-pages/
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
